{{- if .Values.oidc.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nextcloud.fullname" . }}-oidc-conf
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
data:
  oidc.config.php: |
    <?php
    $CONFIG = array (
      'overwrite.cli.url' => 'https://{{ .Values.global.domain }}',
      'overwriteprotocol' => 'https',
      'overwritehost' => '{{ .Values.global.domain }}',
      'trusted_proxies' => array('127.0.0.1', '10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16'),
      'oidc_login_provider_url' => '{{ .Values.oidc.providerUrl }}',
      'oidc_login_client_id' => '{{ .Values.oidc.clientId }}',
      'oidc_login_client_secret' => '{{ .Values.oidc.clientSecret }}',
      'oidc_login_auto_redirect' => {{ .Values.oidc.autoRedirect | default true }},
      'oidc_login_end_session_redirect' => {{ .Values.oidc.endSessionRedirect | default true }},
      'oidc_login_logout_url' => '{{ .Values.oidc.logoutUrl | default (printf "%s/protocol/openid-connect/logout?client_id=%s&post_logout_redirect_uri=https%%3A%%2F%%2F%s%%2F" .Values.oidc.providerUrl .Values.oidc.clientId .Values.global.domain) }}',
      'oidc_login_button_text' => '{{ .Values.oidc.buttonText | default "Log in with Keycloak" }}',
      'oidc_login_disable_registration' => {{ .Values.oidc.disableRegistration | default false }},
      'oidc_login_redir_fallback' => {{ .Values.oidc.redirFallback | default true }},
      'oidc_login_attributes' => array (
        'id' => 'preferred_username',
        'mail' => 'email',
        'name' => 'name',
      ),
      'oidc_login_scope' => '{{ .Values.oidc.scope | default "openid profile email" }}',
      'oidc_login_code_challenge_method' => '{{ .Values.oidc.codeChallengeMethod | default "S256" }}',
      'allow_local_remote_servers' => true,
    );
{{- end }}
