{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-auth
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.password | quote }}
{{- end }}
