{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}-auth
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
stringData:
  mariadb-root-password: {{ .Values.auth.rootPassword | quote }}
  mariadb-password: {{ .Values.auth.password | quote }}
{{- end }}
